In [1]:
import numpy as np
import pandas as pd
import anndata as ad
import os
import sys
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
notes = pd.read_table('../Model_Runs/model_run_notes.txt')

In [3]:
notes.head()

      Runs for included model inputs are as follows:
0                                Low stiffness, +ERL
1  erl_7-7_1_1.csv, erl_7-7_1_2.csv, erl_7-7_1_3.csv
2                               Int. stiffness, +ERL
3  erl_7-7_2_1.csv, erl_7-7_2_2.csv, erl_7-7_2_3.csv
4                               High stiffness, +ERL

In [4]:
cn = notes.iloc[13:37,0].to_list()
cn = [x.split(" ")[1] for x in cn]

In [5]:
cn

['Skp2',
 'p21',
 'p21p',
 'Cdh1',
 'Myc',
 'CycD',
 'CycDp21',
 'Rb',
 'pRb',
 'E2F',
 'RbE2F',
 'CycE',
 'CycEp21',
 'CycA',
 'CycAp21',
 'CycB',
 'CycBp21',
 'Cdc20',
 'BAX',
 'BAXmBCL2',
 'BH3',
 'BH3BCL2',
 'BAXm',
 'BCL2']

In [6]:
file_names = [x for x in os.listdir('../Model_Runs') if not "txt" in x]

In [7]:
file_names

['erl_7-7_3_3.csv',
 'erl_7-7_1_1.csv',
 'erl_7-7_3_2.csv',
 'erl_7-7_1_2.csv',
 'erl_7-7_1_3.csv',
 'erl_7-7_3_1.csv',
 'st_t.csv',
 'dmso_7-7_2.csv',
 'erl_7-7_2_1.csv',
 'dmso_7-7_3.csv',
 'dmso_7-7_1.csv',
 'erl_7-7_2_3.csv',
 'erl_7-7_2_2.csv']

In [8]:
a = pd.read_csv(os.path.join('../Model_Runs',file_names[0]), header=None, names=cn)

In [9]:
a.head()

,Skp2,p21,p21p,Cdh1,Myc,CycD,CycDp21,Rb,pRb,E2F,...,CycAp21,CycB,CycBp21,Cdc20,BAX,BAXmBCL2,BH3,BH3BCL2,BAXm,BCL2
0,20.0,6.0,4.0,2.0000,139.0,45.0,2.0,43.000,130.00,11.0,...,8.0,125.0,1.0,75.0,186.0,13.0,0.0,7.0,0.0,183.0
1,20.0,5.0,4.0,4.0000,138.0,48.0,2.0,41.741,130.26,11.0,...,7.0,128.0,1.0,76.0,186.0,13.0,0.0,7.0,0.0,183.0
2,20.0,5.0,4.0,2.4847,135.0,46.0,3.0,48.000,124.00,7.0,...,6.0,129.0,1.0,79.0,186.0,13.0,0.0,8.0,0.0,182.0
3,21.0,7.0,4.0,1.0000,132.0,44.0,3.0,49.629,122.37,9.0,...,6.0,134.0,1.0,81.0,187.0,12.0,0.0,8.0,0.0,183.0
4,21.0,6.0,5.0,2.6217,135.0,46.0,3.0,52.000,118.00,6.0,...,7.0,137.0,1.0,80.0,188.0,11.0,1.0,7.0,0.0,185.0

In [10]:
a.insert(0, "time", a.index*0.01)

In [11]:
a.head()

,time,Skp2,p21,p21p,Cdh1,Myc,CycD,CycDp21,Rb,pRb,...,CycAp21,CycB,CycBp21,Cdc20,BAX,BAXmBCL2,BH3,BH3BCL2,BAXm,BCL2
0,0.00,20.0,6.0,4.0,2.0000,139.0,45.0,2.0,43.000,130.00,...,8.0,125.0,1.0,75.0,186.0,13.0,0.0,7.0,0.0,183.0
1,0.01,20.0,5.0,4.0,4.0000,138.0,48.0,2.0,41.741,130.26,...,7.0,128.0,1.0,76.0,186.0,13.0,0.0,7.0,0.0,183.0
2,0.02,20.0,5.0,4.0,2.4847,135.0,46.0,3.0,48.000,124.00,...,6.0,129.0,1.0,79.0,186.0,13.0,0.0,8.0,0.0,182.0
3,0.03,21.0,7.0,4.0,1.0000,132.0,44.0,3.0,49.629,122.37,...,6.0,134.0,1.0,81.0,187.0,12.0,0.0,8.0,0.0,183.0
4,0.04,21.0,6.0,5.0,2.6217,135.0,46.0,3.0,52.000,118.00,...,7.0,137.0,1.0,80.0,188.0,11.0,1.0,7.0,0.0,185.0

In [12]:
%matplotlib

Using matplotlib backend: MacOSX

In [13]:
plt.plot(a.iloc[0:10000,]['time'],a.iloc[:10000,]['CycE'])

## cellXgene
For analysis using cellXgene (a project by the Chan-Zuckerberg Initiative), must get data in `anndata` format. See https://anndata.readthedocs.io/en/latest/